# Generated by Django 5.1.7 on 2025-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingChartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_section', models.IntegerField()),
                ('desk_in_row', models.IntegerField()),
                ('desk_in_column', models.IntegerField()),
                ('shuffle', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
